name: 'Terraform Deployment to AWS PROD'

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1 
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"  # Replace with your AWS region

      - name: Terraform Init
        run:  cd ./prod/ && terraform init

      - name: Terraform Validate
        run:  cd ./prod/ && terraform validate

      - name: Terraform Plan
        run:  cd ./prod/ && terraform plan

      - name: Terraform Apply
        run:  cd ./prod/ && terraform apply -auto-approve

